### ISSUE TITLE
Accented character shown for shortcut assignment

### ISSUE THREAD

**Issue by bradchoate** [jessegrosjean/quickcursor#1]
I'm seeing an issue with the QuickCursor menu and my shortcut setting (Ctrl+Shift+E). It winds up with an accent:

<img src="http://img.skitch.com/20091002-8m6eckuemqxsfhbc3iqpa2j4p2.png" />

The shortcut works, however and shows properly in the preferences.

Also interesting... the accent is NOT there upon first display of the menu; only on subsequent views.

I'm running Snow Leopard (10.6.1).

**Comment by jessegrosjean** [comment]
I fixed some related issues, though I'm not sure if this particular issue is fixed or not. Please let me know.

**Comment by bradchoate** [comment]
Sorry; meant to tell you, but this isn't fixed yet.

**Comment by norm** [comment]
I get the same thing (1.1.4, Snow Leopard).

**Comment by jessegrosjean** [comment]
I'm still seeing this error occasionally to. But I have a hard time recreating it when I'm trying to debug. Anyway it's a known issue, but I'm not activly trying to fix it at the moment.

**Comment by jessegrosjean** [comment]
Ok, I think I fixed it this time. Please check out the latest release.

**Comment by norm** [comment]
Yes, that's fixed it for me.

**Comment by bradchoate** [comment]
Yep — fixed!
