### ISSUE TITLE
Document how to be a QuickCursor-capable editor

### ISSUE THREAD

**Issue by jxpx777** [jessegrosjean/quickcursor#12]
Right now, it's not clear what an application needs to implement in order to be a supported editor. I've already edited the info plist in my fork with my bundle identifier, but I'm not clear on what specifics I need to implement beyond that. Any clarification would be most welcome.

**Comment by jessegrosjean** [comment]
Needs to implement the ODB Editor Suite

http://www.barebones.com/support/develop/odbsuite.html

**Comment by jxpx777** [comment]
Thanks, Jesse.
