### ISSUE TITLE
Feature Request: Support for the Byword editor

### ISSUE THREAD

**Issue by ghost** [jessegrosjean/quickcursor#19]
It would be great if QuickCursor had support for the [Byword](http://bywordapp.com) text editor.

**Comment by GreyBurkart** [comment]
Actually, it's a little strange but it's the other way around. Byword needs to support QuickCursor by including the ODB Editor Protocol. Send the Byword devs this link (http://www.barebones.com/support/develop/odbsuite.html) and hopefully they'll include it in a future update.

**Comment by ghost** [comment]
## Oh, ok. Will do. Thanks!

Q: Why is this email three sentences or less?
A: http://three.sentenc.es
