### ISSUE TITLE
Won't build using Xcode 4 because of IB3 ShortcutRecorder Plug-in

### ISSUE THREAD

**Issue by pjones** [jessegrosjean/quickcursor#20]
I'd like to experiment with QuickCursor and see if I can get it working with Emacs (non-Aquamacs) before I buy it.  However, it won't build with Xcode 4.

Would someone please take a look at http://www.osomac.com/2011/03/18/remove-ib-plugins-from-xcode/ and update the Xcode project.  Thanks.

**Comment by GreyBurkart** [comment]
I just tested this, it built and ran in debug mode OK for me from commit 9d77bf1b(...). I installed Xcode 4 right on top of Xcode 3 (the nuclear option) instead of side-by-side. I've saved the link for my own later reference, thanks for posting it!

**Comment by pjones** [comment]
When I open the project file in Xcode 4 I get this error:

Unable to resolve Interface Builder plug-in dependency for "MainMenu.xib". This document requires the net.wafflesoftware.ShortcutRecorder.IB.Leopard Interface Builder 3 plug-in. Consider using Interface Builder 3 to edit this document.

Is it possible that you have uncommitted changes to MainMenu.xib?

**Comment by GreyBurkart** [comment]
Just tried on a fresh clone, same result. That said, I do see the error message when I try to edit the xib, so that needs to be updated in any event. Time to fire up Xcode 3 (which I'd happily deep-sixed, oh well)!

Thanks for pointing this out.

**Comment by GreyBurkart** [comment]
Done, just waiting for Jesse to approve to pull request.
