### ISSUE TITLE
Add support for Sublime Text 2

### ISSUE THREAD

**Issue by franciscolourenco** [jessegrosjean/quickcursor#22]
http://www.sublimetext.com/2

**Comment by GreyBurkart** [comment]
Please see (closed) issue #19: https://github.com/jessegrosjean/quickcursor/issues/19
If it supports the ODB Editor protocol, it can be added to the list!

**Comment by pheraph** [comment]
Sublime 2 now supports ODB protocol, so you might want to add it to the list:

http://www.sublimetext.com/forum/viewtopic.php?f=5&t=4320

**Comment by GreyBurkart** [comment]
Thanks for the heads up. Any idea when the next stable build will come out? I see that support was added to the nightly build 2187, whereas current stable build is 2181.

**Comment by pheraph** [comment]
No idea, but shouldn't take too long as the latest stable betas were released after 2 month of development. You might want to temporarily add the blog feed to your feedreader: http://www.sublimetext.com/blog

**Comment by GreyBurkart** [comment]
Thanks!
