### ISSUE TITLE
Update the text in the target upon file save

### ISSUE THREAD

**Issue by fikovnik** [jessegrosjean/quickcursor#23]
Hi,

First of all, thanks a lot for this app, it works well.

I was just wondering if it would be possible to update the text in the target every time the file in the text editor changes. For example when editing a wiki, it is nice from time to time to hit the preview button to see that everything is fine. Right now I'd need to close the editor to get the text update (unless I'm missing something). If I remember correctly the firefox extension It's all text did that.

Thanks
Filip

**Comment by jessegrosjean** [comment]
Sorry but this isn't really possible with the current implementation... it used normal "Paste" to get the text back into the target... and so the target needs to be the foreground app for that to work, and so that's why it only happens when you close the document in the editor app.

**Comment by fikovnik** [comment]
I completely forget to reply, I'm sorry!

I was thinking that you could detect when the application is back in
focus and then to update the text\* if the underlying file has changed?
But I guess you must have thought about it already.
- (I mean combining the accessibility API to get the focused element
  and then the select all, copy and paste).
