### ISSUE TITLE
Reset focus when done editing

### ISSUE THREAD

**Issue by rsms** [jessegrosjean/quickcursor#3]
## Use case
- reply to a mail in gmail
- initiate editing in TextMate by pressing a shortcut assigned
- write the mail
- close the document in TextMate (or other editor)
### Expected behaviour

Gmail (my browser or whatever application is the editing target) to get primary focus so I can press "Send" or whatever continuation needed to complete an action.
### Actual behaviour

I see my gmail, but TextMate still have focus. I need to use my mouse (trackpad) to click on the browser (gmail) and then back to the keyboard.
## Discussion:

For me, QuickCursor is a feasible tool because of two things:
- It allows me to edit text in a rich editing environment (like now, I'm editing Markdown in TextMate and can see a preview as I write -- very neat).
- Access is quick and I can stick to my keyboard.

Now, the 2nd point above is not really true because the mouse is needed and at least for me that sometimes requires too much _cognitive bandwidth_ to be worth using (e.g. replying to an email).

Anyhow, really great idea and very neat execution! Feels like this could be one of those few tools you just can live without. Thanks.

**Comment by jessegrosjean** [comment]
Thanks, I just added this option in the current release.

**Comment by rsms** [comment]
Neat. FYI I checked out master, opened Xcode 3 and built the default (debug mode) -- failed with 30 errors. Filing an issue with the info.
