### ISSUE TITLE
Add a recently editted files?

### ISSUE THREAD

**Issue by danielhopkins** [jessegrosjean/quickcursor#31]
If something goes wrong in Quick Edit and it fails input your text it would be nice if you could find text that you saved.

On my machine they end up in /var/folders/s3/XXXXXXX.

It would be nice if a list of the recent saved files were in the quick cursor menu item so that you could recover your work.

**Comment by GreyBurkart** [comment]
You can check "Disable clipboard restore" in QuickCursor's preferences to re-enable the old behavior: It overwrites your clipboard contents, but if the paste back fails it's still in your clipboard and can be pasted back with cmd+v manually. I don't believe we have plans to add a link to /var/ temp directories, sorry.

**Comment by danielhopkins** [comment]
Good enough, thank you!
