### ISSUE TITLE
Built binary release file

### ISSUE THREAD

**Issue by jbenet** [jessegrosjean/quickcursor#39]
It would be great to have built releases on github, as described in https://github.com/blog/1547-release-your-software 

It would make it way easier to install (and get others to try it out).

**Comment by jessegrosjean** [comment]
Sorry, I can't right now. I'm on beta OS with beta Xcode only. I'd accept a pull request.

**Comment by jbenet** [comment]
@jessegrosjean would but don't have xcode installed anymore :(. 
Should we leave the issue open so someone can see it + pick it up?

**Comment by GreyBurkart** [comment]
My impression of providing any kind of binary indicates it's being supported and the "pre-release" flag under the GitHub option for that doesn't convey quite the right message. If someone wants to fork this repo and provide their own compiled binary I'd think that's probably covered under the permissive license.

Er, that's just my 2 cents; I'm not speaking for @jessegrosjean on this.

**Comment by jbenet** [comment]
That is an issue of messaging. 
The filename could be very clear. 
Even something extreme like "QuickCursor.UNSUPPORTED.PRERELEASE.zip". 
Could even throw an alert saying so on first launch if still worried about it.
