### ISSUE TITLE
Base editor document title on title of editing textfield's window title

### ISSUE THREAD

**Issue by jxpx777** [jessegrosjean/quickcursor#4]
When editing a textfield from Safari, it would be helpful if the document had the page's title as part of the title. I think it's good to namespace the document with the QuickCursor domain, but the final component could be more intelligent.

My primary use case for this would be Safari. I have a TextMate bundle that I use for more efficient customer service replies and I use it for our email system and our forum system as well. Some of our items are formatted differently for email replies or for forum replies. The best example of this is when the reply includes URLs. In email, the URL goes on its own line so that it's less likely to get munged by the email client. In vBulletin, the URL is linked using bbcode.

When using Edit in TextMate, the title of the document reflected the title of the Safari window so we could have a simple switch to check where the source of the reply was and respond appropriately. This is broken for us in QuickCursor.

**Comment by jessegrosjean** [comment]
I've made the temp file more readable for hte next release.
