### ISSUE TITLE
Support multiple text editors

### ISSUE THREAD

**Issue by norm** [jessegrosjean/quickcursor#6]
Although I mostly use TextMate, it would be nice to have the option to use other editors occasionally. Either by defining multiple editors and keyboard shortcuts or by just having multiple options in the drop-down, with the keyboard shortcut reserved for the primary editor.

**Comment by jessegrosjean** [comment]
This is already possible. Right now it supports

BBEdit, Espresso, MacVim, Smultron, TextMate, TextWrangler, WriteRoom

But it only shows those editors that it supports (and that are installed on your computer) listed in the dropdown menu. So if you install some of the above editors then they to should be listed.

**Comment by norm** [comment]
"But it only shows those editors that it supports" - aha! That'll be what is confusing me. ;)
