### ISSUE TITLE
Request: custom extensions for temporary files

### ISSUE THREAD

**Issue by onecrayon** [jessegrosjean/quickcursor#7]
I'm not sure how you would implement this without interface bloat in the preferences, but I would love to see the ability to map certain extensions to the temporary files created for editing with WriteRoom to more easily take advantage of syntax coloring in editors that rely mainly on extension (Espresso, for me).

For instance, when I'm editing text from OmniWeb, I'm virtually always editing HTML or some HTML derivative, but Espresso sees it as plain text because the temporary file doesn't have an HTML extension.

If I get time back in my life I might grab the source and try to hack this in myself, but in the meantime I figured I'd request it (plus my Objective-C skills are pretty rudimentary at best).  :-)

**Comment by subtleGradient** [comment]
eep. I posted a dupe! http://github.com/jessegrosjean/quickcursor/issues#issue/11

I'm asking for far more though ;)
